server:
  context-path: /tlog # TODO looks like it's ignored when vaadin works
  port: 8080

tlog:
  database:
    name: ~/tlogdb

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:${tlog.database.name};DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect