server:
  context-path: /tlog # TODO looks like it's ignored when vaadin works
  port: 8080

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-update: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect